import { productImages } from "../../utils/share";

export const products = [
    {
        id: 1,
        name: "Green Apple",
        image: productImages.p1,
        price: 14.99,
        originalPrice: 29.99,
        rating: 4.5,
        sale: true,
    },
    {
        id: 2,
        name: "Fresh Indian Malta",
        image: productImages.p2,
        price: 20.0,
        rating: 4,
    },
    {
        id: 3,
        name: "Chinese cabbage",
        image: productImages.p3,
        price: 12.0,
        rating: 4.5,
        active: true,
    },
    {
        id: 4,
        name: "Green Lettuce",
        image: productImages.p4,
        price: 9.0,
        rating: 4.5,
    },
    {
        id: 5,
        name: "Eggplant",
        image: productImages.p5,
        price: 34.0,
        rating: 4.5,
    },
    {
        id: 6,
        name: "Big Potatoes",
        image: productImages.p6,
        price: 20.0,
        rating: 4.5,
    },
    {
        id: 7,
        name: "Corn",
        price: 20.0,
        image: productImages.p7,
        rating: 4,
    },
    {
        id: 8,
        name: "Fresh Cauliflower",
        image: productImages.p8,
        price: 12.0,
        rating: 4.5,
    },
    {
        id: 9,
        name: "Green Capsicum",
        price: 9.0,
        image: productImages.p9,
        originalPrice: 20.99,
        rating: 4,
        sale: true,
    },
    {
        id: 10,
        name: "Green Chili",
        image: productImages.p10,
        price: 34.0,
        rating: 4.5,
    },
]